version: '3'
services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: login_demo
            MYSQL_USER: login_demo
            MYSQL_PASSWORD: password
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"